const RECORDS = window.SIMHIGHLINE_CURVES || [];
const RELATIONS = {
  sfms:{code:"SFMS",title:"Star-forming main sequence",question:"How rapidly do galaxies grow at fixed stellar mass?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(\\mathrm{SFR}/M_\\odot\\,\\mathrm{yr}^{-1})",domain:[8,12]},
  ssfr:{code:"sSFR",title:"Specific star-formation rate",question:"Where does growth give way to quenching?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(\\mathrm{sSFR}/\\mathrm{yr}^{-1})",domain:[8,12]},
  gsmf:{code:"GSMF",title:"Galaxy stellar mass function",question:"How many galaxies does each model build?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(\\Phi/\\mathrm{dex}^{-1}\\,\\mathrm{Mpc}^{-3})",domain:[7,12]},
  quenched:{code:"fQ",title:"Quenched fraction",question:"At what mass does star formation shut down?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"f_\\mathrm{quenched}",domain:[8,12]},
  size:{code:"R-M★",title:"Galaxy mass-size relation",question:"How is stellar mass distributed in space?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(R_{1/2}/\\mathrm{kpc})",domain:[9,12.7]},
  mzr:{code:"MZR",title:"Mass-metallicity relation",question:"How efficiently do galaxies retain the metals they make?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}Z\\;\\mathrm{(native\\ tracer)}",domain:[7,11]},
  shmr:{code:"SHMR",title:"Stellar-halo mass relation",question:"What fraction of a halo becomes stars?",x:"\\log_{10}(M_\\mathrm{halo}/M_\\odot)",y:"\\log_{10}(M_\\star/M_\\mathrm{halo})",domain:[9,13]},
  gas:{code:"fGAS",title:"Cold-gas fraction",question:"Where is the fuel for future star formation?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(M_\\mathrm{gas}/M_\\star)",domain:[8,12]},
  jstar:{code:"j★-M★",title:"Specific angular momentum",question:"How much angular momentum survives in the stellar body?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(j_\\star/\\mathrm{kpc\\,km\\,s}^{-1})",domain:[9,12.7]},
  "hi-fraction":{code:"fHI",title:"Atomic gas fraction",question:"How much atomic hydrogen do galaxies hold at fixed stellar mass?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(M_\\mathrm{HI}/M_\\star)",domain:[9,11.5]},
  "h2-fraction":{code:"fH2",title:"Molecular gas fraction",question:"How much molecular fuel sits in galaxies at fixed stellar mass?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(M_\\mathrm{H_2}/M_\\star)",domain:[9,11.5]},
  smd:{code:"SMD",title:"Cosmic stellar mass density",question:"How fast does the Universe assemble its stars?",x:"z",y:"\\log_{10}\\rho_\\star\\;[M_\\odot\\,\\mathrm{cMpc^{-3}}]",domain:[0,10]},
  bhmd:{code:"BHMD",title:"Cosmic black-hole mass density",question:"When did supermassive black holes grow?",x:"z",y:"\\log_{10}\\rho_\\bullet\\;[M_\\odot\\,\\mathrm{cMpc^{-3}}]",domain:[0,6]},
  zstar:{code:"MZR*",title:"Stellar mass-metallicity relation",question:"How enriched are the stars of a galaxy?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(Z_\\star/Z_\\odot)",domain:[3,12]},
  age:{code:"Age",title:"Stellar age-mass relation",question:"Do massive galaxies form their stars earlier?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(\\mathrm{age/yr})",domain:[8.5,12]},
  himf:{code:"HIMF",title:"HI mass function",question:"How is atomic gas distributed across galaxies?",x:"\\log_{10}(M_\\mathrm{HI}/M_\\odot)",y:"\\log_{10}\\Phi_\\mathrm{HI}",domain:[7,11]},
  sfrf:{code:"SFRF",title:"Star-formation rate function",question:"How common are galaxies at each star-formation rate?",x:"\\log_{10}(\\mathrm{SFR}/M_\\odot\\,\\mathrm{yr}^{-1})",y:"\\log_{10}\\Phi_\\mathrm{SFR}",domain:[-2,3.5]},
  fgas500:{code:"f_gas",title:"Cluster gas fraction (relative to cosmic)",question:"How much of a group or cluster's baryon budget is in hot gas?",x:"\\log_{10}(M_{500c}/M_\\odot)",y:"\\log_{10}[f_\\mathrm{gas,500}/(\\Omega_b/\\Omega_m)]",domain:[12.8,15.5]},
  metald:{code:"rho_Z",title:"Cosmic metal mass density",question:"Where and when are metals produced?",x:"z",y:"\\log_{10}\\rho_Z",domain:[0,10]},
  dmf:{code:"DMF",title:"Dust mass function",question:"How is dust distributed across galaxies?",x:"\\log_{10}(M_\\mathrm{dust}/M_\\odot)",y:"\\log_{10}\\Phi_\\mathrm{dust}",domain:[5,9.5]},
  dtg:{code:"D/G",title:"Dust-to-gas ratio vs metallicity",question:"How efficiently do metals lock into dust?",x:"12+\\log(\\mathrm{O/H})",y:"\\log_{10}(D/G)",domain:[7,9.2]},
  stfr:{code:"M*-Vmax",title:"Stellar mass-halo Vmax relation",question:"How fast do haloes spin at fixed stellar mass?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(V_\\mathrm{max}/\\mathrm{km\\,s^{-1}})",domain:[9,11.5]},
  hmf:{code:"HMF",title:"Halo mass function",question:"How many haloes exist at each mass?",x:"\\log_{10}(M_\\mathrm{halo}/M_\\odot)",y:"\\log_{10}\\Phi_\\mathrm{halo}",domain:[10,15.5]},
  btfr:{code:"BTFR",title:"Baryonic Tully-Fisher relation",question:"Does baryonic mass know the rotation speed?",x:"\\log_{10}(V_\\mathrm{flat}/\\mathrm{km\\,s}^{-1})",y:"\\log_{10}(M_\\mathrm{bar}/M_\\odot)",domain:[1.25,2.75]},
  bh:{code:"MBH-M★",title:"Black-hole-stellar mass relation",question:"How tightly does black-hole growth follow the galaxy?",x:"\\log_{10}(M_\\star/M_\\odot)",y:"\\log_{10}(M_\\mathrm{BH}/M_\\odot)",domain:[9,12.7]},
  bhsigma:{code:"MBH-σ",title:"Black-hole mass-dispersion relation",question:"Does the central potential regulate black-hole growth?",x:"\\log_{10}(\\sigma_\\star/\\mathrm{km\\,s}^{-1})",y:"\\log_{10}(M_\\mathrm{BH}/M_\\odot)",domain:[1.5,2.7]}
};
const INVENTORY={
  "IllustrisTNG TNG100":{records:"IllustrisTNG",short:"TNG100",status:"run locally",relations:"all",note:"Public API and downloadable group catalogs."},
  "IllustrisTNG TNG50":{records:"IllustrisTNG",short:"TNG50",status:"run locally",relations:["sfms","ssfr","mzr","gas","size","jstar","bh"],note:"Higher-resolution public TNG catalogs; smaller volume."},
  "EAGLE Ref-L100N1504":{records:"EAGLE",short:"EAGLE (full)",status:"run locally",relations:"all",note:"Public SQL database; 30 pkpc aperture products. Stellar-halo and size relations are already ingested from the SWIFT comparison data as the EAGLE source."},
  "SIMBA m100n1024":{records:"SIMBA",short:"SIMBA",status:"run locally",relations:["sfms","ssfr","mzr","gas","size","bh","gsmf"],note:"Public snapshots and CAESAR products require definition audit."},
  "ASTRID":{short:"ASTRID",status:"catalog route",relations:["sfms","ssfr","mzr","size","bh","gsmf"],note:"Public FoF/SUBFIND data via PSC and Globus."},
  "FLAMINGO L1_m9":{short:"FLAMINGO",status:"run locally",relations:["sfms","ssfr","size","shmr","bh","gsmf"],note:"Large-volume public release; variants need controlled ingestion."},
  "CAMELS 2P / CV":{short:"CAMELS",status:"corrected catalogs",relations:["sfms","ssfr","mzr","gas","shmr","gsmf"],note:"Corrected multi-suite catalogs; sensitivity rather than census use."},
  "Magneticum Pathfinder":{short:"Magneticum",status:"official tables",relations:"all",note:"Official Box4/uhr medians and intervals currently ingested."},
  "NIHAO zoom suite":{short:"NIHAO",status:"published figures",relations:["gas","shmr","size","jstar","btfr"],note:"Zoom sample with literature relations; not volume complete."},
  "Horizon-AGN":{short:"Horizon-AGN",status:"partial public",relations:["sfms","ssfr","size","bh","bhsigma","quenched","gsmf"],note:"Public mocks; intrinsic galaxy catalogs generally by request."},
  "NewHorizon":{short:"NewHorizon",status:"published figures",relations:["ssfr","mzr","zstar","shmr","size","btfr","gas","bh"],note:"Zoom-in of the Horizon-AGN box; digitized mean relations with errors of the mean, not volume complete."},
  "FIREbox":{records:"FIREbox",short:"FIREbox",status:"published fits",relations:["sfms","ssfr","mzr","gas","shmr","gsmf"],note:"Published relation fits; small volume limits massive systems."},
  "Romulus25":{short:"Romulus25",status:"published figures",relations:["sfms","bh","bhsigma","shmr","quenched"],note:"BH-focused literature evidence; no general catalog endpoint."},
  "THESAN-1":{short:"THESAN-1",status:"official tables",relations:["sfms","mzr","shmr","gsmf"],note:"Official high-redshift relation files currently ingested."},
  "COLIBRE fiducial suite":{records:"COLIBRE",short:"COLIBRE",status:"plot data / literature",relations:["sfms","ssfr","gsmf","quenched","mzr","gas","shmr","size","jstar","bh"],note:"Selected plot data and literature; full release status remains explicit."}
};
const COLORS={"Speagle et al. 2014":"#e9c46a","SPARC / Lelli et al. 2019":"#e9c46a","Kormendy & Ho 2013":"#e9c46a","COSMOS-Web 2025":"#e9c46a","Stott et al. 2013":"#e9c46a","Bradford et al. 2015":"#e9c46a","Popesso et al. 2023":"#f2dc9b","Baldry et al. 2012 (GAMA)":"#f2dc9b","Curti et al. 2020":"#e9c46a","van der Wel et al. 2014":"#e9c46a","Reines & Volonteri 2015":"#e9c46a","THESAN-1":"#67c1cf","Magneticum Pathfinder":"#e69b5e","NIHAO zoom suite":"#a594cf","EAGLE":"#7fb685"};
const SHORT={"Speagle et al. 2014":"Speagle+14","SPARC / Lelli et al. 2019":"SPARC","Kormendy & Ho 2013":"Kormendy-Ho","COSMOS-Web 2025":"COSMOS-Web","Stott et al. 2013":"Stott+13","Bradford et al. 2015":"Bradford+15","Popesso et al. 2023":"Popesso+23","Baldry et al. 2012 (GAMA)":"GAMA Baldry+12","Curti et al. 2020":"Curti+20","van der Wel et al. 2014":"vdWel+14","Reines & Volonteri 2015":"RV15","THESAN-1":"THESAN-1","Magneticum Pathfinder":"Magneticum","NIHAO zoom suite":"NIHAO"};
const MULTI_RUN=new Set(Object.entries(Object.groupBy(RECORDS,r=>`${r.source}|${r.relation}`)).filter(([,rs])=>new Set(rs.map(r=>r.run)).size>1).map(([k])=>k.split("|")[0]));
const unit=r=>MULTI_RUN.has(r.source)?`${r.source} · ${r.run??(r.representation.type==="parametric"?"fit":"data")}`:r.source;
const short=key=>{const [base,run]=key.split(" · ");return (SHORT[base]||base)+(run?` ${run}`:"")};
const KIND_OF=Object.fromEntries(RECORDS.map(r=>[r.source,r.kind]));
const PALETTE={observation:["#e9c46a","#f4a261","#e76f51","#d4a373","#ffb4a2","#b5e48c","#f2cc8f","#e5989b","#ffd166","#a3c4bc","#c9ada7","#f7b267"],"empirical-model":["#c39bd3","#a594cf","#d7bde2"],simulation:["#67c1cf","#e69b5e","#7fb685","#df7669","#5fa8d3","#9ad1a3"]};
const hashOf=text=>[...text].reduce((h,c)=>(h*31+c.charCodeAt(0))>>>0,7);
const SIM_KEYS=[...new Set(RECORDS.filter(r=>r.kind==="simulation").map(unit))].sort();
const SIM_PALETTE=["#67c1cf","#e69b5e","#7fb685","#df7669","#a594cf","#5fa8d3","#d4a5c9","#9ad1a3","#f28482","#84a59d","#bde0fe","#cdb4db","#f6bd60","#90be6d","#43aa8b","#f9844a"];
const colorOf=key=>{const base=key.split(" · ")[0];if(COLORS[key])return COLORS[key];if(KIND_OF[base]==="simulation"){const i=SIM_KEYS.indexOf(key);if(i>=0)return SIM_PALETTE[i%SIM_PALETTE.length]}if(COLORS[base]&&!key.includes(" · "))return COLORS[base];const p=PALETTE[KIND_OF[base]]||PALETTE.observation;return p[hashOf(key)%p.length]};
const representationLabel=r=>r.provenance.tier==="official-table"?(r.kind==="observation"?"official table":"simulation summary"):r.provenance.tier.replaceAll("-"," ");
const availableRelations=Object.keys(RELATIONS);
const state={relation:"sfms",z:0,xMin:9,xMax:11.2,view:"relation",active:new Set(),ref:null};
const {compatible,residuals,summarize,evaluator,interpolate}=window.SimHighlineCompare;
const $=id=>document.getElementById(id);
const svg=(name,attrs={})=>{const el=document.createElementNS("http://www.w3.org/2000/svg",name);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);return el};
const fmt=v=>Number.isInteger(v)?String(v):Number(v).toFixed(v<1?3:2).replace(/0+$/," ").trim().replace(/\.$/,"");
function epochs(){return [...new Set(RECORDS.filter(r=>r.relation===state.relation&&r.epoch.mode!=="analytic-evolution").map(r=>r.epoch.zRepresentative))].sort((a,b)=>a-b)}
function sources(){return Object.entries(INVENTORY).filter(([,s])=>(s.relations==="all"||s.relations.includes(state.relation))&&!(s.records&&RECORDS.some(r=>r.source===s.records&&r.relation===state.relation))).map(([name])=>name).concat([...new Set(RECORDS.filter(r=>r.relation===state.relation).map(unit))].filter(name=>!INVENTORY[name]))}
function selectedRecord(source){
  const candidates=RECORDS.filter(r=>r.relation===state.relation&&unit(r)===source);
  const analytic=candidates.find(r=>r.epoch.mode==="analytic-evolution"&&state.z>=r.epoch.zMin&&state.z<=r.epoch.zMax);if(analytic)return analytic;
  const containing=candidates.find(r=>state.z>=r.epoch.zMin&&state.z<=r.epoch.zMax);if(containing)return containing;
  const nearest=candidates.slice().sort((a,b)=>Math.abs(a.epoch.zRepresentative-state.z)-Math.abs(b.epoch.zRepresentative-state.z))[0];
  return nearest&&Math.abs(nearest.epoch.zRepresentative-state.z)<=.27?nearest:null;
}
function pointsFor(r){
  if(r.representation.type==="points")return r.representation.points.filter(p=>p.x>=state.xMin&&p.x<=state.xMax).map(p=>({...p,sigmaKind:r.representation.intervalKind}));
  const f=evaluator(r),out=[];if(!f)return out;const lo=Math.max(state.xMin,r.domain.xMin),hi=Math.min(state.xMax,r.domain.xMax);for(let i=0;i<140;i++){const x=lo+i/139*(hi-lo),y=f(x,state.z);if(!Number.isFinite(y))continue;const scatter=r.scatter?.value||0;out.push({x,y,yLow:y-scatter,yHigh:y+scatter,sigmaKind:"scatter"})}return out;
}
function activeData(){return sources().filter(s=>state.active.has(s)).map(source=>{const record=selectedRecord(source);return record?{source,record,points:pointsFor(record)}:null}).filter(d=>d&&d.points.length>1)}
function referenceCandidates(data){return data.filter(d=>d.record.kind!=="simulation")}
function reference(data){const c=referenceCandidates(data);return c.find(d=>d.record.id===state.ref)||c.find(d=>d.record.rankable)||null}
function comparison(data){
  const ref=reference(data);if(!ref)return[];
  return data.filter(d=>d.record.kind==="simulation").map(d=>{const check=compatible(d.record,ref.record),res=check.verdict==="not-comparable"?[]:residuals(d.points,ref.points);return{source:d.source,check,res,stats:summarize(res)}})
}
function setRelation(key){state.relation=key;state.ref=null;state.x0=NaN;const rel=RELATIONS[key],es=epochs();state.z=es.length?es[0]:0;[state.xMin,state.xMax]=rel.domain;state.active=new Set(sources());syncHash();render()}
function syncHash(){location.hash=new URLSearchParams({r:state.relation,ref:state.ref||"",sim:state.sim||"",am:state.atlasMode||"",x0:Number.isFinite(state.x0)?state.x0:"",z:state.z,x:`${state.xMin},${state.xMax}`,s:[...state.active].map(s=>short(s)).join(","),v:state.view}).toString()}
function readHash(){const p=new URLSearchParams(location.hash.slice(1));if(availableRelations.includes(p.get("r")))state.relation=p.get("r");const z=Number(p.get("z"));if(Number.isFinite(z))state.z=z;const x=(p.get("x")||"").split(",").map(Number);if(x.length===2&&x.every(Number.isFinite))[state.xMin,state.xMax]=x;else [state.xMin,state.xMax]=RELATIONS[state.relation].domain;state.view=p.get("v")||"relation";state.ref=p.get("ref")||null;state.sim=p.get("sim")||null;state.atlasMode=p.get("am")||"model";state.x0=p.get("x0")?Number(p.get("x0")):NaN;state.active=new Set(sources())}
function renderControls(){
  $("relation").innerHTML=availableRelations.map(k=>`<option value="${k}" ${k===state.relation?"selected":""}>${RELATIONS[k].code} · ${RELATIONS[k].title}</option>`).join("");
  const es=epochs();if(es.length&&!es.some(z=>Math.abs(z-state.z)<1e-5))state.z=es.reduce((a,b)=>Math.abs(b-state.z)<Math.abs(a-state.z)?b:a);
  $("epoch").innerHTML=es.map(z=>`<option value="${z}" ${Math.abs(z-state.z)<1e-5?"selected":""}>z = ${fmt(z)}</option>`).join("")||`<option>analytic</option>`;
  $("xMin").value=state.xMin;$("xMax").value=state.xMax;$("recordCount").textContent=`${RECORDS.length} records`;
  const item=s=>{const r=selectedRecord(s),checked=r&&state.active.has(s),meta=INVENTORY[s],epoch=r?.epoch.mode==="analytic-evolution"?`analytic at z=${fmt(state.z)}`:r?`z=${fmt(r.epoch.zRepresentative)}`:RECORDS.some(x=>x.relation===state.relation&&unit(x)===s)?`no record near z=${fmt(state.z)} (${[...new Set(RECORDS.filter(x=>x.relation===state.relation&&unit(x)===s).map(x=>fmt(x.epoch.zRepresentative)))].slice(0,6).join(", ")})`:meta?.note||"Numerical extraction pending";return `<label class="source-item ${r?"":"inventory-only"}"><input type="checkbox" data-source="${s}" ${checked?"checked":""} ${r?"":"disabled"}><span><b>${short(s)||meta?.short||s}</b><small>${epoch}${r?` · ${r.kind}`:""}</small></span><span class="badge">${r?representationLabel(r):meta?.status||"literature"}</span></label>`};
  const all=sources(),withData=all.filter(s=>RECORDS.some(r=>r.relation===state.relation&&unit(r)===s)),pending=all.filter(s=>!withData.includes(s));
  $("sourceList").innerHTML=withData.map(item).join("")+(pending.length?`<details class="pending"><summary>Mapped, not yet ingested (${pending.length})</summary>${pending.map(item).join("")}</details>`:"");
  document.querySelectorAll("[data-source]").forEach(input=>input.onchange=()=>{input.checked?state.active.add(input.dataset.source):state.active.delete(input.dataset.source);syncHash();renderMain()});
  $("epochStrip").innerHTML=es.map(z=>`<button class="epoch-chip ${Math.abs(z-state.z)<1e-5?"active":""}" data-z="${z}">z ${fmt(z)}</button>`).join("");document.querySelectorAll("[data-z]").forEach(b=>b.onclick=()=>{state.z=Number(b.dataset.z);syncHash();render()});
}
function renderDefinitions(data){
  if(!data.length){$("definitionCheck").innerHTML="<p>No active records.</p>";return}
  const ref=reference(data);if(!ref){$("definitionCheck").innerHTML="<p>No observational reference active; simulations are shown as context only.</p>";return}
  const rows=comparison(data);$("definitionCheck").innerHTML=`<p>Reference: <b>${short(ref.source)||ref.source}</b></p>`+(rows.length?rows.map(c=>`<div class="definition-row ${c.check.verdict==="comparable"?"ok":"warn"}"><p><b>${short(c.source)||c.source}: ${c.check.verdict.replaceAll("-"," ")}</b></p>${[...c.check.blockers,...c.check.caveats].map(t=>`<p>${t}</p>`).join("")}</div>`).join(""):"<p>No active simulation records.</p>");
}
function scales(data,residual=false){const W=1080,H=650,m={l:90,r:28,t:32,b:70},xs=x=>m.l+(x-state.xMin)/(state.xMax-state.xMin)*(W-m.l-m.r);let vals=residual?[]:data.flatMap(d=>d.points.flatMap(p=>[p.y,p.yLow,p.yHigh]).filter(Number.isFinite));if(residual)vals=comparison(data).flatMap(c=>c.res.flatMap(r=>Number.isFinite(r.sigma)?[r.d-r.sigma,r.d+r.sigma]:[r.d]));let lo=Math.min(...vals),hi=Math.max(...vals);if(!vals.length||lo===hi){lo=-1;hi=1}const pad=(hi-lo)*.12;lo-=pad;hi+=pad;const ys=y=>m.t+(hi-y)/(hi-lo)*(H-m.t-m.b);return{W,H,m,xs,ys,lo,hi}}
function path(points,xs,ys,key="y"){return points.map((p,i)=>`${i?"L":"M"}${xs(p.x).toFixed(1)},${ys(p[key]).toFixed(1)}`).join(" ")}
function renderMathNode(parent,tex,x,y,width=380){const fo=svg("foreignObject",{x,y,width,height:28,class:"math-label"}),div=document.createElement("div");div.style.color="#c6cec9";div.style.fontSize="12px";div.textContent=tex;fo.append(div);parent.append(fo);if(window.katex)try{katex.render(tex,div,{throwOnError:false})}catch{}}
function drawChart(data){
  const residual=state.view==="residual",chart=$("chart");chart.innerHTML="";const s=scales(data,residual),{m,xs,ys}=s,plot=svg("g");chart.append(plot);const tickCount=6;
  for(let i=0;i<=tickCount;i++){const y=s.lo+i/tickCount*(s.hi-s.lo),py=ys(y);plot.append(svg("line",{x1:m.l,x2:s.W-m.r,y1:py,y2:py,stroke:"#1d2521"}));const t=svg("text",{x:m.l-10,y:py+3,"text-anchor":"end",fill:"#8f9b94","font-size":10});t.textContent=y.toFixed(Math.abs(s.hi-s.lo)<2?2:1);plot.append(t)}
  for(let i=0;i<=6;i++){const x=state.xMin+i/6*(state.xMax-state.xMin),px=xs(x);plot.append(svg("line",{x1:px,x2:px,y1:m.t,y2:s.H-m.b,stroke:"#1d2521"}));const t=svg("text",{x:px,y:s.H-m.b+20,"text-anchor":"middle",fill:"#8f9b94","font-size":10});t.textContent=x.toFixed(1);plot.append(t)}
  plot.append(svg("line",{x1:m.l,x2:s.W-m.r,y1:s.H-m.b,y2:s.H-m.b,stroke:"#65716b"}));plot.append(svg("line",{x1:m.l,x2:m.l,y1:m.t,y2:s.H-m.b,stroke:"#65716b"}));if(residual&&s.lo<0&&s.hi>0)plot.append(svg("line",{x1:m.l,x2:s.W-m.r,y1:ys(0),y2:ys(0),class:"residual-zero"}));
  const comp=residual?new Map(comparison(data).filter(c=>c.res.length).map(c=>[c.source,c])):null;
  data.forEach(d=>{let pts=d.points;if(residual){const c=comp.get(d.source);if(!c)return;pts=c.res.map(r=>({x:r.x,y:r.d,yLow:r.d-r.sigma,yHigh:r.d+r.sigma}))}const color=colorOf(d.source)||"#aaa",context=!d.record.rankable;
    if(!residual&&pts.some(p=>Number.isFinite(p.yLow)&&Number.isFinite(p.yHigh))){const up=pts.filter(p=>Number.isFinite(p.yHigh)),dn=pts.filter(p=>Number.isFinite(p.yLow)).slice().reverse();if(up.length>1&&dn.length>1)plot.append(svg("path",{d:path(up,xs,ys,"yHigh")+path(dn,xs,ys,"yLow").replace(/^M/,"L")+"Z",fill:color,class:"plot-band"}))}
    if(d.record.representation.type==="parametric"||(d.record.kind==="simulation"&&d.record.provenance.tier!=="digitized-figure")||d.record.representation.connect)plot.append(svg("path",{d:path(pts,xs,ys),stroke:color,class:`plot-line ${context?"context":""}`}));
    if(d.record.representation.type==="points"){pts.forEach(p=>{if(Number.isFinite(p.yLow)&&Number.isFinite(p.yHigh))plot.append(svg("line",{x1:xs(p.x),x2:xs(p.x),y1:ys(p.yLow),y2:ys(p.yHigh),stroke:color,class:"whisker"}));const c=svg("circle",{cx:xs(p.x),cy:ys(p.y),r:d.record.kind==="observation"?3.4:2.5,fill:d.record.kind==="observation"?"#0c100f":color,stroke:color,class:"point"});c.addEventListener("pointermove",e=>showTip(e,`${short(d.source)}<br>x ${p.x.toFixed(2)} · y ${p.y.toFixed(3)}<br>${representationLabel(d.record)}`));c.addEventListener("pointerleave",hideTip);plot.append(c)})}
  });renderMathNode(plot,RELATIONS[state.relation].x,m.l+(s.W-m.l-m.r)/2-120,s.H-34,320);renderMathNode(plot,residual?"\\Delta y\\;\\mathrm{relative\\ to\\ reference}":RELATIONS[state.relation].y,m.l+8,6,480);chart.setAttribute("aria-label",`${RELATIONS[state.relation].title} at redshift ${state.z}`);$("empty").hidden=data.length>0
}
function showTip(e,html){const t=$("tooltip");t.innerHTML=html;t.hidden=false;t.style.left=`${e.clientX+12}px`;t.style.top=`${e.clientY+12}px`}function hideTip(){$("tooltip").hidden=true}
function renderEvidence(data){const plotted=new Map(data.map(d=>[d.source,d]));$("evidenceView").innerHTML=`<table class="evidence-table"><thead><tr><th>Source</th><th>Evidence state</th><th>Epoch</th><th>Definition and status</th></tr></thead><tbody>${sources().map(source=>{const d=plotted.get(source),meta=INVENTORY[source];return d?`<tr><td><b>${d.record.source}</b><small>${d.record.run||"observation"}</small></td><td>${representationLabel(d.record)}<small>${d.record.provenance.tier==="digitized-figure"?"figure extraction":d.record.representation.type}</small></td><td>z = ${fmt(d.record.epoch.zRepresentative)}${d.record.epoch.zNominal!==undefined?`<small>nominal z=${d.record.epoch.zNominal}</small>`:""}</td><td><a href="${d.record.provenance.url}" target="_blank" rel="noreferrer">${d.record.provenance.citation}</a><small>${d.record.rankable?"Eligible for descriptive residuals":"Context only"}. ${d.record.notes||""}</small></td></tr>`:`<tr class="inventory-row"><td><b>${meta?.short||source}</b><small>${source}</small></td><td>${meta?.status||"literature mapped"}<small>not yet a numerical curve</small></td><td>—</td><td>${meta?.note||"Evidence route recorded; numerical extraction pending."}<small>Visible for coverage planning, never drawn as synthetic data.</small></td></tr>`}).join("")}</tbody></table>`}
function renderReadout(data){
  const exact=data.filter(d=>Math.abs(d.record.epoch.zRepresentative-state.z)<1e-5).length;$("epochReadout").innerHTML=`z = ${fmt(state.z)}<small>${exact}/${data.length} records at this exact epoch; nearby matches are labeled.</small>`;
  const cands=referenceCandidates(data),ref=reference(data);$("reference").innerHTML=cands.length?cands.map(d=>`<option value="${d.record.id}" ${ref&&d.record.id===ref.record.id?"selected":""}>${short(d.source)||d.source} · z ${fmt(d.record.epoch.zMin)}–${fmt(d.record.epoch.zMax)}</option>`).join(""):"<option>none active</option>";$("reference").disabled=!cands.length;
  const comp=comparison(data).filter(c=>c.stats);$("metrics").innerHTML=comp.length?comp.map(c=>`<div class="metric"><span>${short(c.source)} · ${c.check.verdict.replaceAll("-"," ")}</span><b>${c.stats.median>=0?"+":""}${c.stats.median.toFixed(3)} dex</b><small>median offset · RMS ${c.stats.rms.toFixed(3)} · ${Number.isFinite(c.stats.meanAbsSigma)?`mean |Δ|/σ ${c.stats.meanAbsSigma.toFixed(1)}${c.stats.sigmaSource==="both"?"":" (reference σ only)"} · `:"σ unavailable · "}${c.stats.n} overlap points</small></div>`).join(""):`<div class="metric na"><span>Residual statistics</span><b>Not applicable</b><small>Requires a definition-compatible simulation and reference with at least ${window.SimHighlineCompare.MIN_BINS} overlapping bins.</small></div>`;
  $("ledger").innerHTML=data.map(d=>`<article class="ledger-card ${d.record.kind==="observation"?"obs":""}"><h3>${short(d.source)}</h3><p>${d.record.axes.yDefinition}</p><p>${d.record.selection.warning||d.record.selection.population||"Selection documented in source."}</p><a href="${d.record.provenance.url}" target="_blank" rel="noreferrer">Source ↗</a><span class="tier">${representationLabel(d.record)} · ${d.record.rankable?"rankable":"context"}</span></article>`).join("")
}
function renderMain(){const rel=RELATIONS[state.relation],data=activeData();$("relationCode").textContent=`${rel.code} · evidence-backed`;$("relationTitle").textContent=rel.title;$("relationQuestion").textContent=rel.question;renderDefinitions(data);renderReadout(data);renderEvidence(data);const plotted=state.view==="relation"||state.view==="residual";$("plotView").hidden=!plotted;$("evidenceView").hidden=state.view!=="evidence";$("extraView").hidden=!EXTRA_VIEWS.has(state.view);document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));if(plotted)drawChart(data);else if(EXTRA_VIEWS.has(state.view))renderExtra();$("caption").textContent=state.view==="residual"?"Residuals are simulation minus the selected reference, linearly interpolated onto overlapping x values, with whiskers combining both reported uncertainties. Only pairs that pass the structured definition check are shown. They are descriptive, not a likelihood or goodness-of-fit score.":"Observational tables are points with reported errors; simulation summaries are connected medians with published percentile envelopes; analytic fits are continuous lines. Figure extractions preserve marker centers or sampled published fits and remain explicitly labeled, with their calibration uncertainty in the evidence record.";$("legend").innerHTML=data.map(d=>`<span class="legend-item" style="color:${colorOf(d.source)}"><i class="legend-swatch ${d.record.representation.type==="points"&&d.record.kind==="observation"?"points":""}"></i>${short(d.source)} · ${representationLabel(d.record)}</span>`).join("")}
function render(){renderControls();renderMain()}
$("relation").onchange=e=>setRelation(e.target.value);$("reference").onchange=e=>{state.ref=e.target.value;syncHash();renderMain()};$("epoch").onchange=e=>{state.z=Number(e.target.value);syncHash();render()};["xMin","xMax"].forEach(id=>$(id).onchange=e=>{state[id]=Number(e.target.value);if(state.xMin>=state.xMax)return;syncHash();renderMain()});$("selectAll").onclick=()=>{state.active=new Set(sources());syncHash();render()};document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;syncHash();renderMain()});$("copyLink").onclick=async()=>{await navigator.clipboard.writeText(location.href);toast("View link copied")};$("exportSvg").onclick=()=>{const copy=$("chart").cloneNode(true),blob=new Blob([new XMLSerializer().serializeToString(copy)],{type:"image/svg+xml"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`sim-highline-${state.relation}-z${state.z}.svg`;a.click();URL.revokeObjectURL(a.href)};$("exportCsv").onclick=()=>{const rows=[["source","run","record_id","z","x","y","y_low","y_high","interval_kind","tier","citation","url"]];for(const d of activeData())for(const p of d.points)rows.push([d.record.source,d.record.run||"",d.record.id,d.record.epoch.mode==="analytic-evolution"?state.z:d.record.epoch.zRepresentative,p.x,p.y,p.yLow??"",p.yHigh??"",d.record.representation.intervalKind||(d.record.representation.type==="parametric"?"fit":""),d.record.provenance.tier,d.record.provenance.citation,d.record.provenance.url]);const csv=rows.map(r=>r.map(v=>{const s=String(v);return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`sim-highline-${state.relation}-z${state.z}.csv`;a.click();URL.revokeObjectURL(a.href)};
$("copyCitations").onclick=async()=>{const seen=new Map();for(const d of activeData()){const p=d.record.provenance;seen.set(p.citation,`${p.citation}${p.doi?` doi:${p.doi}`:""} ${p.url}${p.compilation?` (via ${p.compilation})`:""}`)}await navigator.clipboard.writeText([...seen.values()].join("\n"));toast(`${seen.size} references copied`)};
function toast(message){const t=$("toast");t.textContent=message;t.hidden=false;setTimeout(()=>t.hidden=true,1800)}
readHash();render();window.addEventListener("hashchange",()=>{readHash();render()});
