"""Generate the suite colour tokens (CSS custom properties) for highline/index.html and site/src/site.css.
Eight validated categorical hues (references/palette.md of the dataviz method, validated with validate_palette.js) are assigned to code
families; members of a family differ by lightness (darker in light mode, lighter in dark mode), so colour follows the suite and never its rank.
Run: python3 scripts/make-palette.py > data/palette.css   (the build scripts inline data/palette.css)"""
import math
import re
import sys

LIGHT = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
DARK = ["#3987e5", "#d95926", "#199e70", "#c98500", "#d55181", "#008300", "#9085e9", "#e66767"]
FAMILIES = [["SIMBA", "ASTRID"], ["IllustrisTNG", "Illustris"], ["EAGLE", "COLIBRE", "FLAMINGO"], ["FIRE-2", "FIREbox"], ["NIHAO zoom suite", "Romulus25"],
            ["FLARES", "BlueTides", "Magneticum Pathfinder"], ["THESAN-1", "THESAN-zoom", "SPHINX20"], ["Horizon-AGN", "NewHorizon"]]
STEP = 0.11


def lin(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def gam(c):
    return 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055


def to_oklab(h):
    r, g, b = (lin(int(h[i:i + 2], 16) / 255) for i in (1, 3, 5))
    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b
    l, m, s = (x ** (1 / 3) for x in (l, m, s))
    return (0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s, 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s, 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s)


def from_oklab(L, a, b):
    l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
    m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
    s = (L - 0.0894841775 * a - 1.2914855480 * b) ** 3
    r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    bl = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s
    return "#" + "".join(f"{max(0, min(255, round(gam(max(0, min(1, v))) * 255))):02x}" for v in (r, g, bl))


def shade(h, k, sign):
    """k = 0 the family base; 1 steps toward stronger contrast with the surface (darker on light, lighter on dark); 2 steps the other way."""
    L, a, b = to_oklab(h)
    L2 = max(0.2, min(0.9, L + (sign if k == 1 else -sign if k == 2 else 0) * STEP))
    return from_oklab(L2, a, b)


def de(h1, h2):
    p, q = to_oklab(h1), to_oklab(h2)
    return 100 * math.sqrt(sum((x - y) ** 2 for x, y in zip(p, q)))


def slug(n):
    return re.sub(r"[^a-z0-9]+", "", n.lower())


FLIP = {"IllustrisTNG"}  # this family steps the other way so that dark orange does not meet dark red (Illustris vs NewHorizon)


def block(pal, sign):
    out, members = [], {}
    for fam, base in zip(FAMILIES, pal):
        sg = -sign if fam[0] in FLIP else sign
        cols = [shade(base, k, sg) for k in range(len(fam))]
        members[tuple(fam)] = cols
        out += [f"  --c-{slug(n)}:{c};" for n, c in zip(fam, cols)]
    return out, members


if __name__ == "__main__":
    lo, mlo = block(LIGHT, -1)
    dk, mdk = block(DARK, +1)
    if "--check" in sys.argv:
        for name, mem in (("light", mlo), ("dark", mdk)):
            worst = min((de(c[i], c[j]), fam[i], fam[j]) for fam, c in mem.items() for i in range(len(c)) for j in range(i + 1, len(c)))
            allc = [(n, c) for fam, cols in mem.items() for n, c in zip(fam, cols)]
            cross = min((de(a[1], b[1]), a[0], b[0]) for i, a in enumerate(allc) for b in allc[i + 1:])
            print(name, "within-family min dE %.1f (%s vs %s)" % worst, "| any pair min dE %.1f (%s vs %s)" % cross)
        sys.exit()
    print("/* generated by scripts/make-palette.py: suite colours by code family */")
    print(":root{" + "".join(lo) + "\n  --c-other:#898781;}")
    print("@media (prefers-color-scheme:dark){:root:not([data-theme=\"light\"]){" + "".join(dk) + "\n  --c-other:#898781;}}")
    print(":root[data-theme=\"dark\"]{" + "".join(dk) + "\n  --c-other:#898781;}")
